export type BodyPartKey =
  | 'back'
  | 'cardio'
  | 'chest'
  | 'lower arms'
  | 'lower legs'
  | 'neck'
  | 'shoulders'
  | 'upper arms'
  | 'upper legs'
  | 'waist';

/** Shape emitted by scripts/build-dataset.mjs. Keys are short to keep the payload small. */
export type Exercise = {
  id: string;
  /** Hebrew name, generated by the lexicon in scripts/hebrew-lexicon.mjs */
  he: string;
  /** Original English name from the upstream dataset */
  en: string;
  bp: BodyPartKey;
  eq: string;
  tg: string;
  mg: string;
  sec: string[];
  /** Media basename, resolves to /media/img/{m}.jpg and {cdn}/videos/{m}.gif */
  m: string;
  pat: string;
  lvl: 1 | 2 | 3;
  rank: number;
  comp: 0 | 1;
  timed: 0 | 1;
};

export type Meta = {
  total: number;
  attribution: string;
  bodyParts: { key: BodyPartKey; he: string; short: string }[];
  equipment: { key: string; he: string; chip: string; suffix: string; home: boolean }[];
  targets: Record<string, string>;
  muscles: Record<string, string>;
  patterns: Record<string, { label: string; cues: string[] }>;
  counts: {
    bodyPart: Record<string, number>;
    equipment: Record<string, number>;
    pattern: Record<string, number>;
  };
};

/* ------------------------------------------------------------------ */
/* Profile                                                             */
/* ------------------------------------------------------------------ */

export type Goal = 'muscle' | 'strength' | 'fat' | 'health';
export type Place = 'gym' | 'home' | 'minimal';
export type Level = 1 | 2 | 3;
export type Role = 'trainee' | 'coach';

export type Profile = {
  name: string;
  goal: Goal;
  level: Level;
  days: number;
  place: Place;
  focus: BodyPartKey[];
  role: Role;
  onboarded: boolean;
};

/* ------------------------------------------------------------------ */
/* Programs                                                            */
/* ------------------------------------------------------------------ */

export type Block = {
  exerciseId: string;
  sets: number;
  reps: string;
  rest: number;
  note?: string;
};

export type ProgramDay = {
  id: string;
  name: string;
  subtitle: string;
  blocks: Block[];
};

export type Program = {
  id: string;
  name: string;
  split: string;
  goal: Goal;
  days: ProgramDay[];
  createdAt: number;
  /** 'auto' for the generated plan, 'coach' when a coach assigned it */
  source: 'auto' | 'coach';
  coachName?: string;
  note?: string;
};

/* ------------------------------------------------------------------ */
/* Logging                                                             */
/* ------------------------------------------------------------------ */

export type LoggedSet = {
  weight: number;
  reps: number;
  done: boolean;
};

export type LoggedExercise = {
  exerciseId: string;
  sets: LoggedSet[];
};

export type WorkoutLog = {
  id: string;
  programId: string;
  dayId: string;
  dayName: string;
  startedAt: number;
  endedAt: number;
  entries: LoggedExercise[];
  volume: number;
  sets: number;
  /** Sample data, so it can be cleared without touching real training. */
  demo?: boolean;
};

export type ActiveWorkout = {
  programId: string;
  dayId: string;
  dayName: string;
  startedAt: number;
  index: number;
  entries: LoggedExercise[];
};

/* ------------------------------------------------------------------ */
/* Coach workspace                                                     */
/* ------------------------------------------------------------------ */

export type Trainee = {
  id: string;
  name: string;
  goal: Goal;
  level: Level;
  days: number;
  place: Place;
  joinedAt: number;
  lastActive: number;
  /** Sessions completed out of sessions planned, last 4 weeks */
  done: number;
  planned: number;
  note: string;
  program: Program | null;
  /** Sample data, so it can be cleared without touching real trainees. */
  demo?: boolean;
};
