/**
 * Hebrew lexicon for the exercise dataset.
 *
 * The upstream dataset (hasaneyldrm/exercises-dataset) ships 10 languages, none
 * of them Hebrew. This file is the translation layer: controlled vocabularies
 * are translated exhaustively, and exercise names are rebuilt in Hebrew from a
 * phrase grammar rather than translated word by word (a word-for-word pass
 * produces broken Hebrew word order).
 */

/* ------------------------------------------------------------------ */
/* Controlled vocabularies (complete coverage of the dataset)          */
/* ------------------------------------------------------------------ */

export const BODY_PARTS = {
  back: { he: 'גב', short: 'גב' },
  cardio: { he: 'אירובי', short: 'אירובי' },
  chest: { he: 'חזה', short: 'חזה' },
  'lower arms': { he: 'אמות', short: 'אמות' },
  'lower legs': { he: 'שוקיים', short: 'שוקיים' },
  neck: { he: 'צוואר', short: 'צוואר' },
  shoulders: { he: 'כתפיים', short: 'כתפיים' },
  'upper arms': { he: 'זרועות', short: 'זרועות' },
  'upper legs': { he: 'רגליים', short: 'רגליים' },
  waist: { he: 'ליבה ובטן', short: 'בטן' },
};

export const EQUIPMENT = {
  assisted: { he: 'בעזרת מכשיר', chip: 'מכשיר עזר', suffix: 'בעזרת מכשיר', home: false },
  band: { he: 'גומיית התנגדות', chip: 'גומייה', suffix: 'עם גומייה', home: true },
  barbell: { he: 'מוט', chip: 'מוט', suffix: 'במוט', home: false },
  'body weight': { he: 'משקל גוף', chip: 'משקל גוף', suffix: '', home: true },
  'bosu ball': { he: 'כדור בוסו', chip: 'בוסו', suffix: 'על כדור בוסו', home: false },
  cable: { he: 'כבל', chip: 'כבל', suffix: 'בכבל', home: false },
  dumbbell: { he: 'משקולות יד', chip: 'משקולות', suffix: 'עם משקולות', home: true },
  'elliptical machine': { he: 'אליפטיקל', chip: 'אליפטיקל', suffix: 'באליפטיקל', home: false },
  'ez barbell': { he: 'מוט EZ', chip: 'מוט EZ', suffix: 'במוט EZ', home: false },
  hammer: { he: 'מכונת האמר', chip: 'האמר', suffix: 'במכונת האמר', home: false },
  kettlebell: { he: 'קטלבל', chip: 'קטלבל', suffix: 'עם קטלבל', home: true },
  'leverage machine': { he: 'מכונה', chip: 'מכונה', suffix: 'במכונה', home: false },
  'medicine ball': { he: 'כדור כוח', chip: 'כדור כוח', suffix: 'עם כדור כוח', home: true },
  'olympic barbell': { he: 'מוט אולימפי', chip: 'מוט אולימפי', suffix: 'במוט אולימפי', home: false },
  'resistance band': { he: 'גומיית התנגדות', chip: 'גומייה', suffix: 'עם גומייה', home: true },
  roller: { he: 'גליל עיסוי', chip: 'גליל', suffix: 'על גליל', home: true },
  rope: { he: 'חבל', chip: 'חבל', suffix: 'עם חבל', home: true },
  'skierg machine': { he: 'מכונת סקי', chip: 'סקי-ארג', suffix: 'במכונת סקי', home: false },
  'sled machine': { he: 'מזחלת', chip: 'מזחלת', suffix: 'במזחלת', home: false },
  'smith machine': { he: 'מכונת סמית', chip: 'סמית', suffix: 'בסמית', home: false },
  'stability ball': { he: 'כדור פיזיו', chip: 'כדור פיזיו', suffix: 'על כדור פיזיו', home: true },
  'stationary bike': { he: 'אופני כושר', chip: 'אופניים', suffix: 'על אופני כושר', home: false },
  'stepmill machine': { he: 'מדרגות', chip: 'מדרגות', suffix: 'במכונת מדרגות', home: false },
  tire: { he: 'צמיג', chip: 'צמיג', suffix: 'עם צמיג', home: false },
  'trap bar': { he: 'מוט טראפ', chip: 'מוט טראפ', suffix: 'במוט טראפ', home: false },
  'upper body ergometer': { he: 'ארגומטר ידיים', chip: 'ארגומטר', suffix: 'בארגומטר ידיים', home: false },
  weighted: { he: 'עם משקל נוסף', chip: 'משקל נוסף', suffix: 'עם משקל נוסף', home: true },
  'wheel roller': { he: 'גלגל בטן', chip: 'גלגל בטן', suffix: 'עם גלגל בטן', home: true },
};

export const TARGETS = {
  abductors: 'מקרבי ירך חיצוניים',
  abs: 'שרירי בטן',
  adductors: 'מקרבי ירך',
  biceps: 'דו ראשי',
  calves: 'תאומים',
  'cardiovascular system': 'מערכת לב ריאה',
  delts: 'כתפיים',
  forearms: 'אמות',
  glutes: 'עכוז',
  hamstrings: 'מיתרי ברך',
  lats: 'גב רחב',
  'levator scapulae': 'מרים השכמה',
  pectorals: 'חזה',
  quads: 'ארבע ראשי',
  'serratus anterior': 'משונן קדמי',
  spine: 'זוקפי גב',
  traps: 'טרפז',
  triceps: 'תלת ראשי',
  'upper back': 'גב עליון',
};

export const MUSCLES = {
  abdominals: 'שרירי בטן',
  abs: 'שרירי בטן',
  abductors: 'מקרבי ירך חיצוניים',
  adductors: 'מקרבי ירך',
  'ankle stabilizers': 'מייצבי קרסול',
  ankles: 'קרסוליים',
  back: 'גב',
  biceps: 'דו ראשי',
  brachialis: 'זרועי קדמי',
  calves: 'תאומים',
  'cardiovascular system': 'מערכת לב ריאה',
  chest: 'חזה',
  core: 'שרירי ליבה',
  deltoids: 'כתפיים',
  delts: 'כתפיים',
  feet: 'כפות רגליים',
  forearms: 'אמות',
  glutes: 'עכוז',
  'grip muscles': 'שרירי אחיזה',
  groin: 'מפשעה',
  hamstrings: 'מיתרי ברך',
  hands: 'כפות ידיים',
  'hip flexors': 'כופפי ירך',
  'inner thighs': 'ירך פנימית',
  'latissimus dorsi': 'גב רחב',
  lats: 'גב רחב',
  'levator scapulae': 'מרים השכמה',
  'lower abs': 'בטן תחתונה',
  'lower back': 'גב תחתון',
  obliques: 'שרירים אלכסונים',
  pectorals: 'חזה',
  quadriceps: 'ארבע ראשי',
  quads: 'ארבע ראשי',
  'rear deltoids': 'כתף אחורית',
  rhomboids: 'מקרבי שכמות',
  'rotator cuff': 'שרוול מסובבים',
  'serratus anterior': 'משונן קדמי',
  shins: 'שוקיים קדמיות',
  shoulders: 'כתפיים',
  soleus: 'סוליה',
  spine: 'זוקפי גב',
  sternocleidomastoid: 'שריר הצוואר',
  trapezius: 'טרפז',
  traps: 'טרפז',
  triceps: 'תלת ראשי',
  'upper back': 'גב עליון',
  'upper chest': 'חזה עליון',
  'wrist extensors': 'פושטי שורש',
  'wrist flexors': 'כופפי שורש',
  wrists: 'שורשי כף יד',
};

/* ------------------------------------------------------------------ */
/* Name grammar                                                        */
/* ------------------------------------------------------------------ */

/** Noise removed from names before parsing. */
export const NAME_NOISE = [
  /\((male|female)\)/g,
  /\(version\s*\d+\)/gi,
  /\bv\.?\s*\d+\b/g,
  /\(back pov\)/g,
  /\bpov\b/g,
  /\(vertical\)/g,
];

/**
 * Position / stance phrases. Matched against the name, removed once matched.
 * Order matters: longer phrases first.
 */
export const POSITIONS = [
  ['side lying', 'בשכיבה על הצד'],
  ['lying on floor', 'בשכיבה על הרצפה'],
  ['on the floor', 'על הרצפה'],
  ['on floor', 'על הרצפה'],
  ['bent over', 'בהטיית גו'],
  ['bent-over', 'בהטיית גו'],
  ['bent knee', 'ברכיים כפופות'],
  ['half kneeling', 'בכריעה על ברך אחת'],
  ['kneeling', 'בכריעה'],
  ['standing', 'בעמידה'],
  ['seated', 'בישיבה'],
  ['sitted', 'בישיבה'],
  ['sitting', 'בישיבה'],
  ['supine', 'בשכיבה על הגב'],
  ['prone', 'בשכיבה על הבטן'],
  ['lying', 'בשכיבה'],
  ['reclining', 'בשכיבה'],
  ['incline', 'בשיפוע חיובי'],
  ['decline', 'בשיפוע שלילי'],
  ['flat', 'במישור ישר'],
  ['hanging', 'בתלייה'],
  ['suspended', 'בתלייה'],
  ['squatting', 'בישיבת סקוואט'],
  ['inverted', 'הפוך'],
  ['upright', 'זקופה'],
  ['horizontal', 'אופקי'],
  ['walking', 'בהליכה'],
  ['on bench', 'על ספסל'],
  ['on exercise ball', 'על כדור פיזיו'],
  ['on stability ball', 'על כדור פיזיו'],
  ['on bosu ball', 'על כדור בוסו'],
  ['on a bosu ball', 'על כדור בוסו'],
  ['on wall', 'מול הקיר'],
  ['against wall', 'מול הקיר'],
  ['wall', 'מול הקיר'],
  ['on chair', 'על כיסא'],
  ['over bench', 'על ספסל'],
  ['bench', 'על ספסל'],
  ['floor', 'על הרצפה'],
  ['ground', 'על הרצפה'],
];

/** Grip phrases. */
export const GRIPS = [
  ['shoulder width grip', 'אחיזה ברוחב כתפיים'],
  ['shoulder grip', 'אחיזה ברוחב כתפיים'],
  ['reverse grip', 'אחיזה הפוכה'],
  ['reverse-grip', 'אחיזה הפוכה'],
  ['revers grip', 'אחיזה הפוכה'],
  ['underhand grip', 'אחיזה תחתונה'],
  ['overhand grip', 'אחיזה עליונה'],
  ['neutral grip', 'אחיזה ניטרלית'],
  ['parallel grip', 'אחיזה מקבילה'],
  ['close grip', 'אחיזה צרה'],
  ['close-grip', 'אחיזה צרה'],
  ['narrow grip', 'אחיזה צרה'],
  ['wide grip', 'אחיזה רחבה'],
  ['mixed grip', 'אחיזה מעורבת'],
  ['pronated grip', 'אחיזה פרונטלית'],
  ['supinated grip', 'אחיזה סופינטורית'],
  ['gripless', 'ללא אחיזה'],
  ['underhand', 'אחיזה תחתונה'],
  ['overhand', 'אחיזה עליונה'],
  ['pronated', 'אחיזה פרונטלית'],
  ['supinated', 'אחיזה סופינטורית'],
  ['neutral', 'אחיזה ניטרלית'],
  ['palms up', 'כפות ידיים למעלה'],
  ['palm up', 'כפות ידיים למעלה'],
  ['palms down', 'כפות ידיים למטה'],
  ['palm down', 'כפות ידיים למטה'],
  ['palms in', 'כפות ידיים פנימה'],
  ['behind neck', 'מאחורי הצוואר'],
  ['behind head', 'מאחורי הראש'],
  ['behind the neck', 'מאחורי הצוואר'],
  ['behind the head', 'מאחורי הראש'],
  ['close', 'אחיזה צרה'],
  ['narrow', 'אחיזה צרה'],
  ['wide', 'אחיזה רחבה'],
  ['grip', 'אחיזה'],
];

/** Laterality and tempo phrases. */
export const VARIANTS = [
  ['one arm', 'ביד אחת'],
  ['single arm', 'ביד אחת'],
  ['one-arm', 'ביד אחת'],
  ['two arm', 'בשתי ידיים'],
  ['both arms', 'בשתי ידיים'],
  ['straight arm', 'בזרוע ישרה'],
  ['straight leg', 'ברגל ישרה'],
  ['revers', 'הפוך'],
  ['bent leg', 'ברגל כפופה'],
  ['cross body', 'חוצה גוף'],
  ['one leg', 'ברגל אחת'],
  ['single leg', 'ברגל אחת'],
  ['single-leg', 'ברגל אחת'],
  ['one legged', 'ברגל אחת'],
  ['unilateral', 'צד אחד'],
  ['alternating', 'לסירוגין'],
  ['alternate', 'לסירוגין'],
  ['isometric', 'איזומטרי'],
  ['negative', 'שלב שלילי'],
  ['assisted', 'בסיוע'],
  ['self assisted', 'בסיוע עצמי'],
  ['weighted', 'עם משקל נוסף'],
  ['bodyweight', 'משקל גוף'],
  ['body weight', 'משקל גוף'],
  ['dynamic', 'דינמי'],
  ['static', 'סטטי'],
  ['explosive', 'נפיצה'],
  ['slow', 'איטי'],
  ['partial', 'טווח חלקי'],
  ['quarter', 'רבע טווח'],
  ['half', 'חצי טווח'],
  ['full', 'טווח מלא'],
  ['deep', 'עמוק'],
  ['modified', 'מותאם'],
  ['advanced', 'מתקדם'],
  ['intermediate', 'ביניים'],
  ['basic', 'בסיסי'],
  ['reverse', 'הפוך'],
  ['twisting', 'עם סיבוב'],
  ['twisted', 'עם סיבוב'],
  ['rotational', 'סיבובי'],
  ['circular', 'מעגלי'],
  ['diagonal', 'אלכסוני'],
  ['lateral', 'צידי'],
  ['side', 'צידי'],
  ['front', 'קדמי'],
  ['rear', 'אחורי'],
  ['forward', 'קדימה'],
  ['backward', 'אחורה'],
  ['upward', 'כלפי מעלה'],
  ['overhead', 'מעל הראש'],
  ['low', 'נמוך'],
  ['high', 'גבוה'],
  ['wide stance', 'ברגליים פשוקות'],
  ['sumo', 'סומו'],
  ['staggered', 'ברגליים מדורגות'],
  ['split', 'מפוצל'],
  ['elevated', 'מוגבה'],
  ['jump', 'בקפיצה'],
  ['jumping', 'בקפיצה'],
  ['plyo', 'פליאומטרי'],
  ['with rope attachment', 'עם ידית חבל'],
  ['with v-bar', 'עם ידית V'],
  ['with arm blaster', 'עם ארם בלסטר'],
  ['with straps', 'עם רצועות'],
  ['with towel', 'עם מגבת'],
];

/**
 * Core movement phrases. Longest match wins, so multi-word entries must come
 * before their single-word components.
 */
export const MOVEMENTS = [
  // Chest
  ['bench press', 'לחיצת חזה', 'press-horizontal'],
  ['bench dip', 'מקבילים בספסל', 'dip'],
  ['hammer press', 'לחיצה באחיזה ניטרלית', 'press-horizontal'],
  ['chest press', 'לחיצת חזה', 'press-horizontal'],
  ['chest fly', 'פרפר חזה', 'fly'],
  ['chest dip', 'מקבילים לחזה', 'dip'],
  ['chest push', 'דחיפת חזה', 'press-horizontal'],
  ['chest squeeze', 'לחיצת חזה סוגרת', 'fly'],
  ['pec deck fly', 'פרפר במכונה', 'fly'],
  ['butterfly', 'פרפר במכונה', 'fly'],
  ['crossover', 'קרוסאובר', 'fly'],
  ['crossovers', 'קרוסאובר', 'fly'],
  ['fly', 'פרפר', 'fly'],
  ['flyes', 'פרפר', 'fly'],
  ['guillotine press', 'לחיצת גיליוטינה', 'press-horizontal'],
  ['skull press', 'לחיצה לגולגולת', 'triceps-extension'],
  ['floor press', 'לחיצה מהרצפה', 'press-horizontal'],
  ['push-up', 'שכיבות סמיכה', 'pushup'],
  ['push up', 'שכיבות סמיכה', 'pushup'],
  ['pushup', 'שכיבות סמיכה', 'pushup'],
  ['push-ups', 'שכיבות סמיכה', 'pushup'],
  ['pullover', 'פולאובר', 'pullover'],
  ['pull over', 'פולאובר', 'pullover'],
  ['svend press', 'לחיצת סוונד', 'press-horizontal'],

  // Shoulders
  ['military press', 'לחיצת כתפיים צבאית', 'press-vertical'],
  ['shoulder press', 'לחיצת כתפיים', 'press-vertical'],
  ['overhead press', 'לחיצה מעל הראש', 'press-vertical'],
  ['arnold press', 'לחיצת ארנולד', 'press-vertical'],
  ['bradford press', 'לחיצת ברדפורד', 'press-vertical'],
  ['cuban press', 'לחיצה קובנית', 'press-vertical'],
  ['lateral raise', 'הרחקת כתפיים', 'lateral-raise'],
  ['side lateral raise', 'הרחקת כתפיים', 'lateral-raise'],
  ['front raise', 'הרמה קדמית', 'front-raise'],
  ['t bar row', 'חתירת T', 'row'],
  ['rear delt row', 'חתירת כתף אחורית', 'rear-delt'],
  ['rear delt fly', 'פרפר הפוך', 'rear-delt'],
  ['rear delt raise', 'פרפר הפוך', 'rear-delt'],
  ['rear lateral raise', 'פרפר הפוך', 'rear-delt'],
  ['reverse fly', 'פרפר הפוך', 'rear-delt'],
  ['rear fly', 'פרפר הפוך', 'rear-delt'],
  ['upright row', 'חתירה זקופה', 'upright-row'],
  ['shrug', 'משיכת כתפיים', 'shrug'],
  ['scapular elevation', 'הרמת שכמות', 'shrug'],
  ['scaption', 'הרמה בזווית', 'front-raise'],
  ['face pull', 'משיכה לפנים', 'rear-delt'],
  ['delt raise', 'הרחקת כתפיים', 'lateral-raise'],
  ['deltoid raise', 'הרחקת כתפיים', 'lateral-raise'],
  ['shoulder circles', 'סיבובי כתפיים', 'mobility'],
  ['arm circles', 'סיבובי זרועות', 'mobility'],
  ['internal rotation', 'סיבוב פנימי', 'rotator'],
  ['external rotation', 'סיבוב חיצוני', 'rotator'],
  ['shoulder rotation', 'סיבוב כתף', 'rotator'],

  // Back
  ['lat pulldown', 'משיכת פולי עליון', 'pulldown'],
  ['lateral pulldown', 'משיכת פולי עליון', 'pulldown'],
  ['pulldown', 'משיכת פולי', 'pulldown'],
  ['pull-up', 'מתח', 'pullup'],
  ['pull up', 'מתח', 'pullup'],
  ['pullup', 'מתח', 'pullup'],
  ['chin-up', 'מתח אחיזה תחתונה', 'pullup'],
  ['chin up', 'מתח אחיזה תחתונה', 'pullup'],
  ['muscle up', 'מאסל אפ', 'pullup'],
  ['muscle-up', 'מאסל אפ', 'pullup'],
  ['inverted row', 'חתירה הפוכה', 'row'],
  ['seated row', 'חתירה בישיבה', 'row'],
  ['bent over row', 'חתירה בהטיית גו', 'row'],
  ['pendlay row', 'חתירת פנדליי', 'row'],
  ['renegade row', 'חתירת רנגייד', 'row'],
  ['landmine row', 'חתירת לנדמיין', 'row'],
  ['row', 'חתירה', 'row'],
  ['rack pull', 'משיכה מהמתלה', 'hinge'],
  ['snatch pull', 'משיכת סנאץ', 'olympic'],
  ['high pull', 'משיכה גבוהה', 'olympic'],
  ['deadlift', 'דדליפט', 'hinge'],
  ['dead lift', 'דדליפט', 'hinge'],
  ['good morning', 'גוד מורנינג', 'hinge'],
  ['back extension', 'פשיטת גב', 'back-extension'],
  ['hyperextension', 'הייפר אקסטנשן', 'back-extension'],
  ['hyper extension', 'הייפר אקסטנשן', 'back-extension'],
  ['superman', 'סופרמן', 'back-extension'],
  ['pull down', 'משיכת פולי', 'pulldown'],
  ['straight arm pulldown', 'משיכה בזרועות ישרות', 'pulldown'],

  // Arms
  ['biceps curl', 'כפיפת מרפקים', 'curl'],
  ['bicep curl', 'כפיפת מרפקים', 'curl'],
  ['hammer curl', 'כפיפת פטיש', 'curl'],
  ['preacher curl', 'כפיפת מרפקים בספסל סקוט', 'curl'],
  ['peacher curl', 'כפיפת מרפקים בספסל סקוט', 'curl'],
  ['concentration curl', 'כפיפת ריכוז', 'curl'],
  ['zottman curl', 'כפיפת זוטמן', 'curl'],
  ['drag curl', 'כפיפת גרירה', 'curl'],
  ['spider curl', 'כפיפת ספיידר', 'curl'],
  ['wrist curl', 'כפיפת שורש כף יד', 'wrist'],
  ['reverse curl', 'כפיפה הפוכה', 'curl'],
  ['curl-up', 'כפיפת בטן', 'crunch'],
  ['curl up', 'כפיפת בטן', 'crunch'],
  ['leg curl', 'כפיפת ברכיים', 'leg-curl'],
  ['lower back curl', 'כפיפת גב תחתון', 'back-extension'],
  ['curl', 'כפיפת מרפקים', 'curl'],
  ['curls', 'כפיפת מרפקים', 'curl'],
  ['triceps extension', 'פשיטת מרפקים', 'triceps-extension'],
  ['tricep extension', 'פשיטת מרפקים', 'triceps-extension'],
  ['triceps pushdown', 'פשיטת מרפקים בפולי', 'triceps-extension'],
  ['tricep pushdown', 'פשיטת מרפקים בפולי', 'triceps-extension'],
  ['pushdown', 'פשיטה בפולי', 'triceps-extension'],
  ['kickback', 'בעיטת טרייספס', 'triceps-extension'],
  ['kickbacks', 'בעיטת טרייספס', 'triceps-extension'],
  ['skullcrusher', 'סקאל קראשר', 'triceps-extension'],
  ['skull crusher', 'סקאל קראשר', 'triceps-extension'],
  ['jm press', "לחיצת JM", 'triceps-extension'],
  ['tate press', 'לחיצת טייט', 'triceps-extension'],
  ['dip', 'מקבילים', 'dip'],
  ['dips', 'מקבילים', 'dip'],
  ['leg extension', 'פשיטת ברכיים', 'leg-extension'],
  ['extension', 'פשיטה', 'triceps-extension'],
  ['wrist extension', 'פשיטת שורש כף יד', 'wrist'],
  ['wrist rotation', 'סיבוב שורש כף יד', 'wrist'],
  ['pronation', 'פרונציה', 'wrist'],
  ['supination', 'סופינציה', 'wrist'],
  ['finger curl', 'כפיפת אצבעות', 'wrist'],
  ['gripper', 'מכשיר אחיזה', 'wrist'],

  // Legs
  ['front squat', 'סקוואט קדמי', 'squat'],
  ['back squat', 'סקוואט אחורי', 'squat'],
  ['hack squat', 'האק סקוואט', 'squat'],
  ['split squat', 'סקוואט מפוצל', 'lunge'],
  ['sissy squat', 'סיסי סקוואט', 'squat'],
  ['goblet squat', 'סקוואט גובלט', 'squat'],
  ['zercher squat', 'סקוואט זרשר', 'squat'],
  ['jefferson squat', "סקוואט ג'פרסון", 'squat'],
  ['pistol squat', 'סקוואט פיסטול', 'squat'],
  ['cossack squat', 'סקוואט קוזאק', 'squat'],
  ['squat', 'סקוואט', 'squat'],
  ['squats', 'סקוואט', 'squat'],
  ['leg press', 'לחיצת רגליים', 'leg-press'],
  ['calf press', 'לחיצת תאומים', 'calf'],
  ['donkey calf raise', 'הרמת עקבים בהטיית גו', 'calf'],
  ['calf raise', 'הרמת עקבים', 'calf'],
  ['calf raises', 'הרמת עקבים', 'calf'],
  ['heel raise', 'הרמת עקבים', 'calf'],
  ['toe raise', 'הרמת בהונות', 'calf'],
  ['lunge', 'מכרעים', 'lunge'],
  ['lunges', 'מכרעים', 'lunge'],
  ['step up', 'עלייה על מדרגה', 'lunge'],
  ['step-up', 'עלייה על מדרגה', 'lunge'],
  ['glute bridge', 'גשר עכוז', 'hip-thrust'],
  ['hip thrust', 'הרמת אגן', 'hip-thrust'],
  ['hip raise', 'הרמת אגן', 'hip-thrust'],
  ['hip extension', 'פשיטת ירך', 'hip-thrust'],
  ['pelvic tilt', 'הטיית אגן', 'core'],
  ['bridge', 'גשר', 'hip-thrust'],
  ['hip abduction', 'הרחקת ירך', 'abduction'],
  ['hip adduction', 'קירוב ירך', 'adduction'],
  ['abduction', 'הרחקת ירך', 'abduction'],
  ['adduction', 'קירוב ירך', 'adduction'],
  ['leg raise', 'הרמת רגליים', 'leg-raise'],
  ['leg raises', 'הרמת רגליים', 'leg-raise'],
  ['knee raise', 'הרמת ברכיים', 'leg-raise'],
  ['high knee', 'ברכיים גבוהות', 'cardio'],
  ['flutter kick', 'בעיטות פרפר', 'leg-raise'],
  ['scissor kick', 'בעיטות מספריים', 'leg-raise'],
  ['donkey kick', 'בעיטת חמור', 'glute'],
  ['glute kickback', 'בעיטת עכוז', 'glute'],
  ['femoral', 'כפיפת ברכיים', 'leg-curl'],
  ['thruster', 'תראסטר', 'olympic'],
  ['clean and jerk', "קלין אנד ג'רק", 'olympic'],
  ['clean', 'קלין', 'olympic'],
  ['snatch', 'סנאץ', 'olympic'],
  ['jerk', "ג'רק", 'olympic'],
  ['swing', 'סווינג', 'olympic'],
  ['box jump', 'קפיצה לקופסה', 'plyo'],
  ['depth jump', 'קפיצת עומק', 'plyo'],
  ['jump squat', 'סקוואט בקפיצה', 'plyo'],
  ['jumping jack', 'קפיצות פישוק', 'cardio'],
  ['jack', 'קפיצות פישוק', 'cardio'],
  ['burpee', 'ברפי', 'cardio'],
  ['skater hops', 'קפיצות סקייטר', 'plyo'],
  ['star jump', 'קפיצת כוכב', 'plyo'],

  // Core
  ['russian twist', 'טוויסט רוסי', 'twist'],
  ['side crunch', 'כפיפת בטן צידית', 'crunch'],
  ['oblique crunch', 'כפיפת בטן אלכסונית', 'crunch'],
  ['bicycle crunch', 'כפיפת בטן אופניים', 'crunch'],
  ['reverse crunch', 'כפיפת בטן הפוכה', 'crunch'],
  ['crunch', 'כפיפת בטן', 'crunch'],
  ['crunches', 'כפיפות בטן', 'crunch'],
  ['cocoons', 'קוקון', 'crunch'],
  ['sit-up', 'כפיפות בטן מלאות', 'crunch'],
  ['sit up', 'כפיפות בטן מלאות', 'crunch'],
  ['situp', 'כפיפות בטן מלאות', 'crunch'],
  ['jackknife', 'סכין מתקפל', 'crunch'],
  ['jack knife', 'סכין מתקפל', 'crunch'],
  ['v up', 'V אפ', 'crunch'],
  ['v sit', 'ישיבת V', 'core'],
  ['sit ups', 'כפיפות בטן מלאות', 'crunch'],
  ['push ups', 'שכיבות סמיכה', 'pushup'],
  ['pull ups', 'מתח', 'pullup'],
  ['chin ups', 'מתח אחיזה תחתונה', 'pullup'],
  ['pike push up', 'שכיבות סמיכה בפייק', 'pushup'],
  ['side plank', 'פלאנק צידי', 'plank'],
  ['plank', 'פלאנק', 'plank'],
  ['side bridge', 'גשר צידי', 'plank'],
  ['mountain climber', 'מטפס הרים', 'cardio'],
  ['dead bug', 'דד באג', 'core'],
  ['bird dog', 'בירד דוג', 'core'],
  ['hollow hold', 'החזקת הולו', 'core'],
  ['rollerout', 'גלגול בטן', 'core'],
  ['rollerer', 'גלגול בטן', 'core'],
  ['roll out', 'גלגול בטן', 'core'],
  ['fallout', 'גלגול בטן', 'core'],
  ['ab wheel', 'גלגל בטן', 'core'],
  ['pallof press', 'לחיצת פאלוף', 'core'],
  ['windmill', 'טחנת רוח', 'core'],
  ['wood chop', 'חיטוב עצים', 'twist'],
  ['twist', 'סיבוב גו', 'twist'],
  ['twists', 'סיבובי גו', 'twist'],
  ['side bend', 'הטיה צידית', 'core'],
  ['side bends', 'הטיות צידיות', 'core'],
  ['bend', 'הטיה', 'core'],
  ['wipers', 'מגבים', 'core'],
  ['heel touchers', 'נגיעות בעקבים', 'crunch'],
  ['toe touch', 'נגיעה בבהונות', 'core'],
  ['tuck', 'קיפול ברכיים', 'crunch'],
  ['l sit', 'ישיבת L', 'core'],
  ['flag', 'דגל', 'core'],
  ['planche', 'פלאנש', 'core'],
  ['handstand', 'עמידת ידיים', 'core'],
  ['skin the cat', 'סקין דה קאט', 'core'],
  ['bear crawl', 'זחילת דוב', 'cardio'],
  ['crawl', 'זחילה', 'cardio'],
  ['inchworm', 'תולעת מדידה', 'mobility'],

  // Neck
  ['neck flexion', 'כפיפת צוואר', 'neck'],
  ['neck extension', 'פשיטת צוואר', 'neck'],

  // Cardio
  ['run', 'ריצה', 'cardio'],
  ['sprint', 'ספרינט', 'cardio'],
  ['sprints', 'ספרינטים', 'cardio'],
  ['walk', 'הליכה', 'cardio'],
  ['ski', 'סקי', 'cardio'],
  ['cycle', 'רכיבה', 'cardio'],
  ['stair climb', 'טיפוס מדרגות', 'cardio'],
  ['rope climb', 'טיפוס חבל', 'cardio'],
  ['battling ropes', 'חבלי קרב', 'cardio'],
  ['drag', 'גרירה', 'carry'],
  ['carry', 'נשיאה', 'carry'],
  ['farmers walk', 'הליכת חקלאי', 'carry'],
  ['slam', 'הטחה', 'plyo'],
  ['throw', 'זריקה', 'plyo'],

  // Mobility and stretching
  ['stretch', 'מתיחה', 'stretch'],
  ['pose', 'תנוחה', 'stretch'],
  ['cobra', 'תנוחת קוברה', 'stretch'],
  ['sphinx', 'תנוחת ספינקס', 'stretch'],
  ['downward facing dog', 'כלב מביט מטה', 'stretch'],
  ['upward facing dog', 'כלב מביט מעלה', 'stretch'],
  ['hug', 'חיבוק', 'stretch'],
  ['scapular retraction', 'קירוב שכמות', 'mobility'],
  ['scapula retractor', 'קירוב שכמות', 'mobility'],
  ['scapula depresor', 'הורדת שכמות', 'mobility'],
  ['balance', 'שיווי משקל', 'mobility'],
  ['march', 'צעידה במקום', 'mobility'],
  ['raise', 'הרמה', 'front-raise'],
  ['lift', 'הרמה', 'front-raise'],
  ['press', 'לחיצה', 'press-vertical'],
  ['presses', 'לחיצה', 'press-vertical'],
  ['pull', 'משיכה', 'row'],
  ['push', 'דחיפה', 'press-horizontal'],
  ['kick', 'בעיטה', 'plyo'],
  ['kicks', 'בעיטות', 'plyo'],
  ['rotation', 'סיבוב', 'mobility'],
];

/**
 * Fallback token dictionary for words that survive phrase matching.
 * Anything not here is dropped from the Hebrew name rather than left in Latin.
 */
export const TOKENS = {
  arm: 'זרוע',
  arms: 'זרועות',
  leg: 'רגל',
  legs: 'רגליים',
  knee: 'ברך',
  knees: 'ברכיים',
  hip: 'ירך',
  hips: 'ירכיים',
  glute: 'עכוז',
  glutes: 'עכוז',
  gluteus: 'עכוז',
  chest: 'חזה',
  back: 'גב',
  shoulder: 'כתף',
  shoulders: 'כתפיים',
  biceps: 'דו ראשי',
  bicep: 'דו ראשי',
  triceps: 'תלת ראשי',
  tricep: 'תלת ראשי',
  quad: 'ארבע ראשי',
  quads: 'ארבע ראשי',
  hamstring: 'מיתר ברך',
  hamstrings: 'מיתרי ברך',
  calf: 'תאומים',
  calves: 'תאומים',
  abs: 'בטן',
  ab: 'בטן',
  abdominal: 'בטן',
  oblique: 'אלכסונים',
  lat: 'גב רחב',
  lats: 'גב רחב',
  trap: 'טרפז',
  traps: 'טרפז',
  spine: 'עמוד שדרה',
  neck: 'צוואר',
  wrist: 'שורש כף יד',
  wrists: 'שורשי כף יד',
  forearm: 'אמה',
  ankle: 'קרסול',
  ankles: 'קרסוליים',
  groin: 'מפשעה',
  piriformis: 'פיריפורמיס',
  'rectus femoris': 'ארבע ראשי',
  peroneals: 'פרונאלים',
  tibialis: 'שוק קדמית',
  hand: 'יד',
  hands: 'ידיים',
  head: 'ראש',
  elbow: 'מרפק',
  finger: 'אצבע',
  feet: 'כפות רגליים',
  toe: 'בהונות',
  heel: 'עקב',
  body: 'גוף',
  bar: 'מוט',
  bars: 'מוטות',
  bench: 'ספסל',
  ball: 'כדור',
  chair: 'כיסא',
  floor: 'רצפה',
  board: 'לוח',
  box: 'קופסה',
  platform: 'משטח',
  stepbox: 'מדרגה',
  step: 'מדרגה',
  staircase: 'מדרגות',
  cage: 'כלוב',
  rack: 'מתלה',
  pad: 'כרית',
  strap: 'רצועה',
  straps: 'רצועות',
  handle: 'ידית',
  attachment: 'ידית',
  pulley: 'גלגלת',
  machine: 'מכונה',
  trainer: 'מכשיר',
  equipment: 'ציוד',
  ring: 'טבעות',
  rings: 'טבעות',
  towel: 'מגבת',
  wheel: 'גלגל',
  roller: 'גליל',
  sled: 'מזחלת',
  sledge: 'מזחלת',
  tire: 'צמיג',
  rope: 'חבל',
  ropes: 'חבלים',
  band: 'גומייה',
  stirrups: 'ארכובות',
  treadmill: 'הליכון',
  stepmill: 'מכונת מדרגות',
  elliptical: 'אליפטיקל',
  ergometer: 'ארגומטר',
  skier: 'מכונת סקי',
  stationary: 'נייח',
  boxing: 'איגרוף',
  yoga: 'יוגה',
  judo: 'ג׳ודו',
  turkish: 'טורקי',
  korean: 'קוריאני',
  hindu: 'הינדי',
  french: 'צרפתי',
  london: 'לונדון',
  cuban: 'קובני',
  archer: 'קשת',
  frog: 'צפרדע',
  crab: 'סרטן',
  gorilla: 'גורילה',
  monster: 'מפלצת',
  stork: 'חסידה',
  swimmer: 'שחיין',
  runners: 'רצים',
  runner: 'רץ',
  clock: 'שעון',
  diamond: 'יהלום',
  pyramid: 'פירמידה',
  star: 'כוכב',
  spider: 'עכביש',
  bear: 'דוב',
  cat: 'חתול',
  dog: 'כלב',
  cobra: 'קוברה',
  butt: 'ישבן',
  potty: 'סיר',
  prisoner: 'אסיר',
  waiter: 'מלצר',
  kayak: 'קייאק',
  bowling: 'באולינג',
  tennis: 'טניס',
  world: 'עולם',
  greatest: 'הגדולה',
  wind: 'רוח',
  speed: 'מהירות',
  quick: 'מהיר',
  short: 'קצר',
  stride: 'צעד',
  motion: 'תנועה',
  range: 'טווח',
  position: 'תנוחה',
  support: 'תמיכה',
  supported: 'נתמך',
  stabilization: 'ייצוב',
  fixed: 'קבוע',
  stance: 'עמידה',
  apart: 'פשוקות',
  clasped: 'שלובות',
  outstretched: 'פשוטות',
  extended: 'פשוטה',
  raised: 'מורמות',
  bent: 'כפופה',
  straight: 'ישרה',
  stiff: 'נוקשה',
  romanian: 'רומני',
  vertical: 'אנכי',
  angled: 'בזווית',
  angle: 'זווית',
  degrees: 'מעלות',
  inner: 'פנימי',
  outer: 'חיצוני',
  upper: 'עליון',
  lower: 'תחתון',
  middle: 'אמצעי',
  posterior: 'אחורי',
  anterior: 'קדמי',
  double: 'כפול',
  single: 'בודד',
  two: 'שתי',
  three: 'שלוש',
  twin: 'תאום',
  seesaw: 'נדנדה',
  release: 'שחרור',
  catch: 'תפיסה',
  drop: 'הורדה',
  hang: 'תלייה',
  hold: 'החזקה',
  squeeze: 'סחיטה',
  reach: 'הושטה',
  touch: 'נגיעה',
  tap: 'נקישה',
  slide: 'החלקה',
  flip: 'היפוך',
  around: 'סביב',
  through: 'דרך',
  between: 'בין',
  above: 'מעל',
  under: 'מתחת',
  outside: 'מחוץ',
  inside: 'בתוך',
  down: 'למטה',
  up: 'למעלה',
  off: 'מחוץ',
  air: 'אוויר',
  gravity: 'כבידה',
  anti: 'אנטי',
  self: 'עצמי',
  power: 'כוח',
  pro: 'מקצועי',
  basic: 'בסיסי',
  variation: 'וריאציה',
  sequence: 'רצף',
  multiple: 'מרובה',
  response: 'תגובה',
  drive: 'הנעה',
  thrusts: 'דחיפות',
  pass: 'העברה',
  point: 'נקודה',
  figure: 'צורה',
  round: 'עגול',
  semi: 'חצי',
  impossible: 'בלתי אפשרי',
  wall: 'קיר',
  hammer: 'פטיש',
  cross: 'מוצלב',
  inverse: 'הפוך',
  parallel: 'מקביל',
  delt: 'כתף',
  deltoid: 'כתף',
  chin: 'סנטר',
  flexor: 'כופף',
  zottman: 'זוטמן',
  pike: 'פייק',
  scapula: 'שכמות',
  scapular: 'שכמות',
  hack: 'האק',
  landmine: 'לנדמיין',
  iron: 'ברזל',
  face: 'פנים',
  rocking: 'מתנדנד',
  bottoms: 'תחתון',
  straddle: 'פישוק',
  jumps: 'קפיצות',
  raises: 'הרמות',
  bends: 'הטיות',
  hook: 'הוק',
  left: 'שמאל',
  right: 'ימין',
  concentration: 'ריכוז',
  russian: 'רוסי',
  guillotine: 'גיליוטינה',
  bradford: 'ברדפורד',
  cossack: 'קוזאק',
  pistol: 'פיסטול',
  kipping: 'קיפינג',
  stalder: 'סטאלדר',
  maltese: 'מלטזי',
  scissor: 'מספריים',
  flutter: 'פרפור',
  saw: 'מסור',
  lean: 'נטייה',
  external: 'חיצוני',
  rotate: 'סיבוב',
  rotary: 'סיבובי',
  pec: 'חזה',
  pectoralis: 'חזה',
  adductor: 'מקרב',
  abductor: 'מרחיק',
  circles: 'סיבובים',
  flexion: 'כפיפה',
  rocky: 'רוקי',
  slingers: 'סלינגרס',
  sternum: 'עצם החזה',
  contralateral: 'נגדי',
  elevator: 'מעלית',
  captains: 'כיסא הקפטן',
  clap: 'מחיאת כף',
  curtsey: 'קידה',
  big: 'גדול',
  closer: 'צמוד',
  benches: 'ספסלים',
  lifting: 'הרמה',
  pin: 'פין',
  cambered: 'מעוקל',
};

/** Function words dropped silently instead of being reported as unknown. */
export const STOPWORDS = new Set([
  'with', 'on', 'the', 'and', 'to', 'from', 'in', 'a', 'of', 'for', 'into',
  'against', 'over', 'under', 'out', 'off', 'all', 'both', 'can', 'plus',
  'across', 'through', 'between', 'above', 'below', 'v', 'male', 'female',
  'pov', 'exercise', 'variation', 'style', 'get', 'reps', 'ups', 'one', 'two',
  'lever', 'palm', 'sit', 'squad', 'fours', 'astride', 'forth', 'supper',
  'major', 'rectus', 'femoris', 'stability', 'bosu', 'cable', 'bike', 'keens',
]);

/* ------------------------------------------------------------------ */
/* Movement-pattern coaching cues (authored Hebrew)                    */
/* ------------------------------------------------------------------ */

/**
 * Hebrew form cues per movement pattern. The upstream dataset has no Hebrew
 * instructions, so these authored cues are the primary Hebrew guidance; the
 * original English steps stay available in the exercise sheet.
 */
export const PATTERN_CUES = {
  'press-horizontal': {
    label: 'דחיפה אופקית',
    cues: [
      'שכמות מכווצות ולחוצות אל המשענת לאורך כל החזרה.',
      'הורידו את המשקל בשליטה עד מגע קל בחזה, בקצב של שתי שניות.',
      'מרפקים בזווית של כ 45 מעלות מהגוף, לא פתוחים לצדדים.',
      'דחפו כלפי מעלה תוך נעיצת כפות הרגליים ברצפה.',
    ],
  },
  'press-vertical': {
    label: 'דחיפה אנכית',
    cues: [
      'הדקו את הבטן והעכוז כדי למנוע קשת בגב התחתון.',
      'התחילו כשהמוט בגובה הסנטר והמרפקים מעט מלפנים.',
      'דחפו מעלה עד יישור מלא של המרפקים, הראש עובר קדימה בסוף התנועה.',
      'הורידו בשליטה, בלי להפיל את המשקל על הכתפיים.',
    ],
  },
  fly: {
    label: 'פתיחת חזה',
    cues: [
      'שמרו על כיפוף קבוע וקל במרפקים לאורך כל התנועה.',
      'פתחו לצדדים עד מתיחה נעימה בחזה, בלי לרדת מתחת לגובה הכתפיים.',
      'סגרו בקשת רחבה תוך חשיבה על סחיטת החזה פנימה.',
      'המשקל כאן קטן יותר מבלחיצה. הטווח חשוב מהעומס.',
    ],
  },
  pullover: {
    label: 'פולאובר',
    cues: [
      'הורידו את המשקל מאחורי הראש בשליטה עד מתיחה בגב הרחב.',
      'הצלעות סגורות והבטן מהודקת, בלי לפתוח קשת בגב.',
      'משכו חזרה בעזרת הגב, לא בעזרת המרפקים.',
    ],
  },
  pushup: {
    label: 'שכיבות סמיכה',
    cues: [
      'הגוף בקו ישר אחד מהעקבים ועד הראש.',
      'כפות הידיים מעט רחבות מהכתפיים, אצבעות קדימה.',
      'רדו עד שהחזה כמעט נוגע ברצפה, מרפקים אחורה ולא לצדדים.',
      'דחפו את הרצפה מכם והדקו את העכוז בסיום.',
    ],
  },
  dip: {
    label: 'מקבילים',
    cues: [
      'התחילו מיישור מלא של המרפקים וכתפיים מורדות.',
      'רדו עד זווית של 90 מעלות במרפק, בלי לצנוח.',
      'הטיית גו קדימה מדגישה חזה, גו זקוף מדגיש תלת ראשי.',
      'עצרו את הירידה לפני כאב בקדמת הכתף.',
    ],
  },
  row: {
    label: 'משיכה אופקית',
    cues: [
      'משכו את המרפקים אחורה לכיוון הירכיים, לא את הידיים.',
      'סיימו כל חזרה בכיווץ שכמות אחת לשנייה.',
      'הגב נשאר ישר, התנועה מגיעה מהזרועות ולא מהגב התחתון.',
      'הורידו בשליטה עד מתיחה מלאה של הגב.',
    ],
  },
  pulldown: {
    label: 'משיכה אנכית',
    cues: [
      'החזה פתוח כלפי מעלה והמבט קדימה.',
      'משכו את המוט אל קו עצם הבריח, לא אל הבטן.',
      'חשבו על הורדת המרפקים לכיוון הכיסים.',
      'שחררו לאט עד מתיחה מלאה של הגב הרחב.',
    ],
  },
  pullup: {
    label: 'מתח',
    cues: [
      'התחילו מתלייה מלאה עם שכמות פעילות.',
      'משכו עד שהסנטר עובר את המוט, בלי בעיטות.',
      'הרגליים שלובות והבטן מהודקת כדי למנוע נדנוד.',
      'ירידה איטית של שלוש שניות בונה כוח מהר יותר.',
    ],
  },
  squat: {
    label: 'סקוואט',
    cues: [
      'רגליים ברוחב אגן, בהונות מעט החוצה.',
      'שברו קודם בירכיים ואז בברכיים, המשקל על אמצע כף הרגל.',
      'רדו עד שהירך מקבילה לרצפה או נמוך יותר, אם הניידות מאפשרת.',
      'הברכיים נעות בקו הבהונות, בלי לקרוס פנימה.',
    ],
  },
  hinge: {
    label: 'הינג׳ ירכיים',
    cues: [
      'המוט צמוד לגוף לאורך כל התנועה.',
      'דחפו את הירכיים אחורה, הגב נשאר ישר וניטרלי.',
      'הדקו בטן וסגרו את בית השחי לפני שאתם מרימים.',
      'סיימו בנעילת ירכיים ועכוז, בלי לפתוח קשת בגב.',
    ],
  },
  lunge: {
    label: 'מכרעים',
    cues: [
      'צעד גדול מספיק כדי שהברך הקדמית תישאר מעל הקרסול.',
      'רדו אנכית עד שהברך האחורית כמעט נוגעת ברצפה.',
      'הגו זקוף, המבט קדימה, הבטן מהודקת.',
      'דחפו דרך העקב של הרגל הקדמית בחזרה למעלה.',
    ],
  },
  'leg-press': {
    label: 'לחיצת רגליים',
    cues: [
      'הגב התחתון צמוד למשענת לאורך כל התנועה.',
      'רדו עד 90 מעלות בברך, בלי לגלגל את האגן מהמשענת.',
      'דחפו דרך העקבים ואל תנעלו את הברכיים בכוח.',
    ],
  },
  'leg-extension': {
    label: 'פשיטת ברכיים',
    cues: [
      'ציר המכונה מיושר לגובה הברך.',
      'יישרו את הברכיים באופן מלא ועצרו רגע בכיווץ.',
      'הורידו לאט, בלי להפיל את המשקל.',
    ],
  },
  'leg-curl': {
    label: 'כפיפת ברכיים',
    cues: [
      'האגן צמוד לכרית, בלי להרים את הישבן.',
      'כפפו עד הסוף וכווצו את מיתרי הברך לרגע.',
      'הורידו בשליטה של שלוש שניות.',
    ],
  },
  calf: {
    label: 'תאומים',
    cues: [
      'טווח מלא: מתיחה מלאה למטה ועלייה מקסימלית על הבהונות.',
      'עצרו שנייה בנקודה הגבוהה בכל חזרה.',
      'קצב איטי ואחיד, בלי קפיצות.',
    ],
  },
  'hip-thrust': {
    label: 'הרמת אגן',
    cues: [
      'הצלעות סגורות למטה, המבט על הברכיים.',
      'דחפו דרך העקבים והדקו עכוז חזק בנקודה העליונה.',
      'עצרו שנייה למעלה, ירידה בשליטה.',
    ],
  },
  glute: {
    label: 'עכוז',
    cues: [
      'האגן מיושר לרצפה, בלי לסובב את הגו.',
      'התנועה יוצאת מהירך, לא מהגב התחתון.',
      'כווצו את העכוז בסוף כל חזרה.',
    ],
  },
  abduction: {
    label: 'הרחקת ירך',
    cues: [
      'הגו זקוף ויציב, התנועה רק בירך.',
      'פתחו לאט עד סוף הטווח הנוח וכווצו.',
      'החזירו בשליטה בלי להרפות את המתח.',
    ],
  },
  adduction: {
    label: 'קירוב ירך',
    cues: [
      'התחילו מטווח פתוח נוח, בלי מתיחה כואבת.',
      'סגרו את הרגליים בשליטה וכווצו את פנים הירך.',
      'החזירו לאט לעמדת ההתחלה.',
    ],
  },
  curl: {
    label: 'כפיפת מרפקים',
    cues: [
      'המרפקים צמודים לגוף ולא נעים קדימה.',
      'כפפו עד כיווץ מלא בלי להניע את הגו.',
      'הורידו לאט עד יישור כמעט מלא של המרפק.',
      'אם הגב מתנדנד, המשקל כבד מדי.',
    ],
  },
  'triceps-extension': {
    label: 'פשיטת מרפקים',
    cues: [
      'המרפקים קבועים במקום, רק האמה זזה.',
      'ישרו את המרפק עד הסוף וכווצו את התלת ראשי.',
      'החזירו בשליטה עד מתיחה מלאה.',
    ],
  },
  'lateral-raise': {
    label: 'הרחקת כתפיים',
    cues: [
      'הרימו עד גובה הכתפיים בלבד, לא מעבר.',
      'כיפוף קל וקבוע במרפק, האגודל מעט מטה.',
      'הובילו עם המרפק ולא עם כף היד.',
      'הורידו לאט. משקל קטן עובד כאן טוב יותר.',
    ],
  },
  'front-raise': {
    label: 'הרמה קדמית',
    cues: [
      'הרימו עד גובה העיניים בקצב אחיד.',
      'בלי תנופה מהגב או מהברכיים.',
      'הורידו בשליטה עד הירכיים.',
    ],
  },
  'rear-delt': {
    label: 'כתף אחורית',
    cues: [
      'הטיית גו קדימה עם גב ישר.',
      'פתחו לצדדים בכיפוף קל במרפק, שכמות נעות אחורה.',
      'עצרו רגע בכיווץ והורידו לאט.',
    ],
  },
  'upright-row': {
    label: 'חתירה זקופה',
    cues: [
      'משכו עד גובה החזה בלבד, לא עד הסנטר.',
      'המרפקים מובילים ונשארים מעל גובה כף היד.',
      'אחיזה ברוחב כתפיים מפחיתה עומס על הכתף.',
    ],
  },
  shrug: {
    label: 'משיכת כתפיים',
    cues: [
      'הרימו את הכתפיים ישר למעלה לכיוון האוזניים.',
      'בלי סיבובי כתף. התנועה אנכית בלבד.',
      'עצרו שנייה למעלה והורידו לאט.',
    ],
  },
  rotator: {
    label: 'שרוול מסובבים',
    cues: [
      'מרפק צמוד לגוף בזווית 90 מעלות.',
      'תנועה איטית עם משקל קטן, זה שריר מייצב.',
      'עצרו בסוף הטווח בלי כאב.',
    ],
  },
  wrist: {
    label: 'אמות',
    cues: [
      'האמה נתמכת, רק כף היד נעה.',
      'טווח מלא בשני הכיוונים, בקצב איטי.',
      'משקלים קטנים וחזרות גבוהות עובדים הכי טוב.',
    ],
  },
  crunch: {
    label: 'כפיפות בטן',
    cues: [
      'גלגלו את עמוד השדרה כלפי מעלה, לא מושכים את הצוואר.',
      'נשפו בעלייה וכווצו את הבטן חזק.',
      'רדו לאט מבלי להניח לגמרי את הגב.',
    ],
  },
  'leg-raise': {
    label: 'הרמת רגליים',
    cues: [
      'הגב התחתון צמוד לרצפה או לכרית.',
      'הרימו בשליטה, בלי תנופה.',
      'הורידו עד לפני שהגב מתנתק ואז עלו שוב.',
    ],
  },
  plank: {
    label: 'פלאנק',
    cues: [
      'מרפקים מתחת לכתפיים, גוף בקו ישר אחד.',
      'הדקו בטן ועכוז, האגן לא צונח ולא מתרומם.',
      'נשימה רגילה ורציפה לאורך ההחזקה.',
    ],
  },
  core: {
    label: 'ליבה',
    cues: [
      'הצלעות סגורות והבטן מהודקת לאורך כל התנועה.',
      'האגן יציב, התנועה מבוקרת ואיטית.',
      'עדיף פחות חזרות עם שליטה מלאה.',
    ],
  },
  twist: {
    label: 'סיבוב גו',
    cues: [
      'הסיבוב מגיע מהגו העליון, האגן נשאר יציב.',
      'תנועה מבוקרת, בלי להעיף את המשקל מצד לצד.',
      'נשפו בכל סיבוב.',
    ],
  },
  'back-extension': {
    label: 'פשיטת גב',
    cues: [
      'עלו עד קו ישר עם הגוף, בלי לפתוח קשת מעבר לכך.',
      'הבטן מהודקת והצוואר בהמשך לעמוד השדרה.',
      'קצב איטי בשני הכיוונים.',
    ],
  },
  neck: {
    label: 'צוואר',
    cues: [
      'טווח קטן ומבוקר, בלי תנופה.',
      'עצרו מיד אם מרגישים נימול או כאב חד.',
      'משקל מינימלי וחזרות איטיות.',
    ],
  },
  olympic: {
    label: 'הרמה אולימפית',
    cues: [
      'התנועה מתחילה מהרגליים, לא מהידיים.',
      'המוט צמוד לגוף לאורך כל המשיכה.',
      'למדו את התרגיל עם מוט ריק לפני שמוסיפים משקל.',
    ],
  },
  plyo: {
    label: 'פליאומטרי',
    cues: [
      'נחיתה רכה על אמצע כף הרגל עם ברכיים מעט כפופות.',
      'איכות לפני כמות. עצרו כשהקפיצה מאבדת גובה.',
      'מנוחה מלאה בין הסטים.',
    ],
  },
  cardio: {
    label: 'אירובי',
    cues: [
      'התחילו בחימום קל של שלוש עד חמש דקות.',
      'שמרו על קצב שמאפשר לכם לדבר במשפטים קצרים.',
      'סיימו בהרפיה הדרגתית ולא בעצירה פתאומית.',
    ],
  },
  carry: {
    label: 'נשיאה',
    cues: [
      'כתפיים אחורה ולמטה, הגו זקוף.',
      'צעדים קצרים ויציבים, מבט קדימה.',
      'האחיזה היא הגורם המגביל. עצרו כשהיא מאבדת יציבות.',
    ],
  },
  stretch: {
    label: 'מתיחה',
    cues: [
      'החזיקו 20 עד 30 שניות בכל צד.',
      'מתיחה נעימה, לא כואבת.',
      'נשמו עמוק ורגוע לאורך ההחזקה.',
    ],
  },
  mobility: {
    label: 'ניידות',
    cues: [
      'תנועה איטית בטווח מלא ונוח.',
      'בלי תנופה ובלי כאב חד.',
      'מתאים כחלק מחימום לפני האימון.',
    ],
  },
  general: {
    label: 'כללי',
    cues: [
      'בצעו את התנועה בקצב מבוקר בשני הכיוונים.',
      'שמרו על גב ניטרלי ובטן מהודקת.',
      'עצרו סט אחד לפני כישלון טכני.',
    ],
  },
};
